### ISSUE TITLE
Can not compile and test the id

### ISSUE THREAD

**Issue by mageddo** [davecheney/junk#2]
I've try [this link](http://stackoverflow.com/a/32115271/2979435) but no success

```bash
$ cd github.com/davecheney/junk/id
$ cd go test .
can't load package: package .: C source files not allowed when not using cgo or SWIG: id.c
```
My machine details

```
go version go1.6.3 linux/amd64

gcc version
gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


```

**Comment by mageddo** [comment]
My go env

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/elvis/dev/projects/go-mageddo"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by davecheney** [comment]
This code doesn't compile any more, that's why it's in the junk repo.

**Comment by mageddo** [comment]
@davecheney Aw, so why did it not works anymore?

**Comment by davecheney** [comment]
> can't load package: package .: C source files not allowed when not using
cgo or SWIG: id.c

The support for using C code (in the old 6c compiler style) was removed
when the Go compiler was converted to Go.

**Comment by mageddo** [comment]
@davecheney Ok, Please what go version compiles this code?

**Comment by davecheney** [comment]
Probably Go 1.5 or earlier.

**Comment by davecheney** [comment]
Just to be clear. This package is in my junk repo because the code is not something that should be used.

**Comment by mageddo** [comment]
@davecheney shure, thanks
