### ISSUE TITLE
how to compile the go-id program

### ISSUE THREAD

**Issue by ORESoftware** [davecheney/junk#4]
I am trying to compile and run the go program to retrieve goroutine ids, i filed this ticket too

Issue #4 on t-yuki/goid
https://github.com/t-yuki/goid/issues/4

**Comment by davecheney** [comment]
@ORESoftware what did you try? What did you see when you tried?

**Comment by ORESoftware** [comment]
a readme with instructions, even if only for yourself when you try to compile it in 3 years. Last time I tried compiling it said it was missing `runtime.h` which is a golang related file to compile C programs? i don't know much about C, I just want to get it to work and use it in a Go program. thx.

**Comment by davecheney** [comment]
It's likely this code does not compile any more. Sorry, i'm not going to fix it, you're welcome to fork the repo.
